### ISSUE TITLE
Nice App - Suggestion

### ISSUE THREAD

**Issue by tyeeman** [BazzaCuda/ffmpegparams#6]
Thanks for writing this. Been looking for a GUI for ffmpeg that I can use my own command line switches. Most of my command lines are very long. Would it be possible to locate the output switches drop down to another place so that long lines are viewable? Maybe at the bottom?

**Comment by BazzaCuda** [comment]
Hi. Glad to hear I'm not the only one that finds this app useful :P

Release v1.1.0 is available for download - make sure you don't overwrite your .ini file with the one in the zip file.

An excellent suggestion, thanks.

I've moved both switch boxes to the middle so that the workflow is still top-to-bottom and made them both significantly longer/wider.

Let me know what you think.

**Comment by tyeeman** [comment]
Very nice, thanks for the quick update. One other thing comes to mind. Do you know of Rigaya's nvenc encoder. It's also very good and it would be nice to make it work with your GUI. I'm thinking a simple way would be a couple of radio buttons, one for "ffmpeg" and one for "other". Actually this may make it work for any command line app. Below radio button "other" have a text field to enter the name of any executable, like "nvencc" then you can program your GUI to use either "ffmpeg" or "nvencc" in this example, or any other .exe. What do you think?

**Comment by BazzaCuda** [comment]
Interesting idea. I shall investigate :P

**Comment by BazzaCuda** [comment]
Done! v2.0.0 released.
I did a quick test using NVEncC64, with just -i as the only input option, and -o as the only output option - it worked well.

The app automatically clears the contents of the Log Level box if you select an exe other than FFMPEG.

Let me know how you get on.

**Comment by tyeeman** [comment]
This is great. I will try it tonight! Thanks again!

**Comment by tyeeman** [comment]
It seems to be working great. The only thing that comes to mind to improve would be to label the output switches for a reminder what they are encoding for. Like "Blu-ray 2k" or "Blu-ray 4k". 

Do you think it's necessary. How do you currently determine what output switches to use?

**Comment by tyeeman** [comment]
Hey, I found an easy way to name presets! Just type them in the .ini file in the line before the output switches you want. Like so...
![2024-04-19_175545](https://github.com/BazzaCuda/ffmpegparams/assets/4469306/652ee13a-b526-43e0-95f6-fee76f7b94df)

**Comment by BazzaCuda** [comment]
Ha! What a great idea 🥳
